database:
  user:
    model: User
    uid:
      user_uid_ifield: id
    usernames:
      username_sfield: username
    passwords:
      plain_text_sfield: nil
      encrypted_sfield: encrypted_password
    cookies:
      token_sfield: remember_token
      expires_tfield: remember_token_expires_at
  role:
    model: Role
    user_linkage:
      relationship_type: [many_to_many,one_to_many,local]
      relationship_name: roles
    role_code_ifield: code
  roles_user:
    model: RolesUser
    linkage:
      user_id_ifield: user_id
      role_id_ifield: role_id
authentication:
  encryption: [md5,sha1,none]
  password_match: [encrypted_field,plain_text_field]
  auth_post: true
  auth_session: true
  auth_cookie: true
  helpers:
    authenticated_method: authenticated
    password_method: storePassword
    encryption_method: encrypt
    authenticate_method: authenticate
  post_login:
    post_form_field: login
    post_username_field: username
    post_password_field: password
  session_login:
    uid_field: user_uid
static_roles:
  filter_policy: [white_list, black_list]
