database:
  user:
    model: User
    uid:
      user_uid: id
    usernames:
      username_sfield: username
    passwords:
      plain_text_sfield: nil
      encrypted_sfield: encrypted_password
    cookies:
      token_sfield: remember_token
      expires_tfield: remember_token_expires_at
    role_relationship: roles
  role:
    model: RoleUser
    role_code_ifield: code
    user_id_ifield: user_id
    user_relationship: user
authentication:
  encryption: [md5,sha1,none]
  password_match: [encrypted_sfield,plain_text_sfield]
  auth_post: true
  auth_session: true
  auth_cookie: true
  helpers:
    authenticated_method: authenticated?
    password_method: storePassword
    encryption_method: encrypt
    authenticate_method: authenticate
  post_login:
    post_form_field: login
    post_username_field: username
    post_password_field: password
  session_login:
    uid_field: user_uid
static_roles:
  filter_policy: [white_list, black_list]
